# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdiff < Formula
  desc "Kubernetes resource differ"
  homepage "https://github.com/rajamohan-rj/kdiff"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajamohan-rj/kdiff/releases/download/v1.0.1/kdiff_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "0ee67603cd6ba5e78ecdcccf385f04d65bfe98cf6ef73d3da69fbfd09a28e93d"

      def install
        bin.install "kdiff" => "kdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajamohan-rj/kdiff/releases/download/v1.0.1/kdiff_1.0.1_Darwin_arm64.tar.gz"
      sha256 "7659199bceccdab5d703ca7cbdcb7ca63fe15ccdeb50e47acc610b1b809ad2c5"

      def install
        bin.install "kdiff" => "kdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajamohan-rj/kdiff/releases/download/v1.0.1/kdiff_1.0.1_Linux_x86_64.tar.gz"
      sha256 "b6a18379c25bb8ace78998abd247fe1c7bd2cbd6319b31832179e813d1669016"
      def install
        bin.install "kdiff" => "kdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajamohan-rj/kdiff/releases/download/v1.0.1/kdiff_1.0.1_Linux_arm64.tar.gz"
      sha256 "a49812a8c8221881cf5e883399a7faee702a9ff2cf36c087ab04b61f591209ad"
      def install
        bin.install "kdiff" => "kdiff"
      end
    end
  end

  test do
    system "#{bin}/kdiff", "--version"
  end
end
