# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfrun < Formula
  desc "Git-aware Terraform runner"
  homepage "https://github.com/rajamohan-rj/test-tfrun"
  version "1.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajamohan-rj/test-tfrun/releases/download/v1.0.13/test-tfrun_1.0.13_Darwin_x86_64.tar.gz"
      sha256 "7fd5af3f6b89cd01daa930b99155b9f8317d98d5c2c7a41080288f1a281fe982"

      def install
        bin.install "test-tfrun" => "tfrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajamohan-rj/test-tfrun/releases/download/v1.0.13/test-tfrun_1.0.13_Darwin_arm64.tar.gz"
      sha256 "10f9ce2173c3f8de088a04ff209faf41c1fd09e8adac089d36b4a4b2e638ddbd"

      def install
        bin.install "test-tfrun" => "tfrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajamohan-rj/test-tfrun/releases/download/v1.0.13/test-tfrun_1.0.13_Linux_x86_64.tar.gz"
      sha256 "62ca26537720ca40e47bd3d3f432dc5f2b0c62e0fc26bf59ee15b5712cfeb0ec"
      def install
        bin.install "test-tfrun" => "tfrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajamohan-rj/test-tfrun/releases/download/v1.0.13/test-tfrun_1.0.13_Linux_arm64.tar.gz"
      sha256 "3f9795f63444f9c49aad660c3b99adfa55e538aa6629cbab2d5303f511368210"
      def install
        bin.install "test-tfrun" => "tfrun"
      end
    end
  end

  test do
    system "#{bin}/tfrun", "--version"
  end
end
