# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfrun < Formula
  desc "Git-aware Terraform runner"
  homepage "https://github.com/rajamohan-rj/tfrun"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajamohan-rj/tfrun/releases/download/v1.0.1/tfrun_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "7e5687e5bbdb8a88a677b450cfbf38f457fb5b953de09b80823f919f1571b0d6"

      def install
        bin.install "tfrun" => "tfrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajamohan-rj/tfrun/releases/download/v1.0.1/tfrun_1.0.1_Darwin_arm64.tar.gz"
      sha256 "2e591585017252f68cb026ee443d40fa00a338d1ffec4e9d1e5502ed8a692c2c"

      def install
        bin.install "tfrun" => "tfrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajamohan-rj/tfrun/releases/download/v1.0.1/tfrun_1.0.1_Linux_x86_64.tar.gz"
      sha256 "a85561e2c136d8b712636fe151e4e29bcc4ff2101b846047710aa2b0c1201060"
      def install
        bin.install "tfrun" => "tfrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajamohan-rj/tfrun/releases/download/v1.0.1/tfrun_1.0.1_Linux_arm64.tar.gz"
      sha256 "611bc8d5404af3514a574842f8d0abce402cbfeb238a0a6ea145f3c27c40aa71"
      def install
        bin.install "tfrun" => "tfrun"
      end
    end
  end

  test do
    system "#{bin}/tfrun", "--version"
  end
end
